//! Command line definitions using clap derive.
//!
//! Help is not generated by clap. It is printed from src/bin/inu_r132_help.txt
//! (see src/bin/inu_r132.rs).

use std::path::PathBuf;

use clap::{Parser, Subcommand, ValueEnum};

use crate::inu::{OutputFormat, StreamKind};
use crate::protocol::StreamMode;

/// Pixel format requested from the camera.
#[derive(Clone, Copy, Debug, ValueEnum, PartialEq, Eq)]
pub enum FormatArg {
    Bgra,
    Bgr,
    Rgba,
}

impl From<FormatArg> for OutputFormat {
    fn from(value: FormatArg) -> Self {
        match value {
            FormatArg::Bgra => OutputFormat::Bgra,
            FormatArg::Bgr => OutputFormat::Bgr,
            FormatArg::Rgba => OutputFormat::Rgba,
        }
    }
}

/// Which streams `serve` opens.
#[derive(Clone, Copy, Debug, ValueEnum, PartialEq, Eq)]
pub enum StreamArg {
    Rgb,
    Depth,
    /// Open every stream the camera has, so clients can switch without a restart.
    All,
    /// Open rgb and depth and let subscribers overlay them.
    Mix,
}

impl StreamArg {
    /// Bitmask of `StreamKind` bits to open.
    pub fn mask(self) -> u32 {
        match self {
            StreamArg::Rgb => StreamKind::Rgb.bit(),
            StreamArg::Depth => StreamKind::Depth.bit(),
            StreamArg::All | StreamArg::Mix => StreamKind::mask(&StreamKind::ALL),
        }
    }

    /// Mode a subscriber gets when it does not ask for one.
    pub fn default_mode(self) -> StreamMode {
        match self {
            StreamArg::Depth => StreamMode::Depth,
            StreamArg::Mix => StreamMode::Mix,
            _ => StreamMode::Rgb,
        }
    }
}

/// Which stream the local CLI viewer shows first.
#[derive(Clone, Copy, Debug, ValueEnum, PartialEq, Eq)]
pub enum DisplayStreamArg {
    Rgb,
    Depth,
}

impl From<DisplayStreamArg> for StreamKind {
    fn from(value: DisplayStreamArg) -> Self {
        match value {
            DisplayStreamArg::Rgb => StreamKind::Rgb,
            DisplayStreamArg::Depth => StreamKind::Depth,
        }
    }
}

/// Inuitive NU4000 R132 (CGS_132 RGB) camera protocol server and viewer
#[derive(Parser, Debug)]
#[command(
    name = "inu-r132",
    version,
    about,
    long_about = None,
    disable_help_flag = true,
    disable_help_subcommand = true
)]
pub struct Cli {
    /// Show help, the content comes from src/bin/inu_r132_help.txt
    #[arg(long, short = 'h')]
    pub help: bool,

    #[command(subcommand)]
    pub command: Option<Command>,
}

#[derive(Subcommand, Debug)]
pub enum Command {
    /// Start Inuitive's InuService daemon and serve the R132 camera over TCP.
    /// Frames are pushed as JPEG to every `subscribe`d client, commands are
    /// newline terminated UTF-8 (see the README for the wire format)
    #[command(disable_help_flag = true)]
    Serve {
        /// TCP port to listen on
        #[arg(long, default_value_t = crate::wire::DEFAULT_PORT)]
        port: u16,

        /// JPEG frames per second pushed to subscribers (0 = unlimited)
        #[arg(long, default_value_t = 30)]
        fps: u32,

        /// JPEG quality, 1..=100
        #[arg(long, default_value_t = 80, value_parser = clap::value_parser!(u8).range(1..=100))]
        quality: u8,

        /// Do not start InuService; connect to the already running daemon
        #[arg(long)]
        attach: bool,

        /// Serve a synthetic moving pattern instead of the camera, for testing
        /// the protocol and `display --remote` without any hardware
        #[arg(long)]
        mock: bool,

        /// Stream raw depth instead of registering it to the RGB camera. Depth
        /// is registered by default (ActivateRegisteredDepth), so `mix` lines up
        /// without any manual offset; pass this to see the raw sensor depth
        #[arg(long)]
        no_registered: bool,

        /// InuService name to connect to (default: auto)
        #[arg(long, value_name = "NAME")]
        service: Option<String>,

        /// Pixel format requested from the SDK
        #[arg(long, value_enum, default_value_t = FormatArg::Bgra)]
        format: FormatArg,

        /// Which streams to publish: rgb (JPEG), depth (raw Z16), all or mix.
        /// `all` opens every stream so clients can switch; `mix` also makes
        /// subscribers default to the rgb+depth overlay
        #[arg(long, value_enum, default_value_t = StreamArg::Rgb)]
        stream: StreamArg,

        /// RGB channel id to stream from (default: auto detect)
        #[arg(long, allow_negative_numbers = true)]
        channel: Option<i32>,
    },

    /// Show the RGB camera in a window. Without --remote this opens the local
    /// NU4000; with --remote it displays a stream served by another host
    #[command(disable_help_flag = true)]
    Display {
        /// `HOST:PORT` of an `inu-r132 serve` to display instead of the local
        /// camera. Without a value it connects to 0.0.0.0:5534, i.e. a serve on
        /// this machine
        #[arg(
            long,
            value_name = "HOST:PORT",
            num_args = 0..=1,
            default_missing_value = "0.0.0.0:5534"
        )]
        remote: Option<String>,

        /// InuService name to connect to (default: auto)
        #[arg(long, value_name = "NAME")]
        service: Option<String>,

        /// Requested frame rate, 0 = sensor default
        #[arg(long, default_value_t = 0)]
        fps: u32,

        /// Pixel format requested from the SDK
        #[arg(long, value_enum, default_value_t = FormatArg::Bgra)]
        format: FormatArg,

        /// Stream shown first; 1/2 switch streams in the window
        #[arg(long, value_enum, default_value_t = DisplayStreamArg::Rgb)]
        stream: DisplayStreamArg,

        /// Depth display window near edge in mm (bright end)
        #[arg(long, default_value_t = 300)]
        near: u16,

        /// Depth display window far edge in mm (dark end)
        #[arg(long, default_value_t = 5000)]
        far: u16,

        /// Depth greyscale curve: 1.0 is linear, below 1.0 brightens the middle
        /// (useful when most of the scene is far away)
        #[arg(long, default_value_t = 1.0)]
        gamma: f32,

        /// Start with the depth window auto-ranged to the 2%..98% percentile
        /// of each frame instead of the fixed --near/--far
        #[arg(long)]
        auto: bool,

        /// Stream raw depth instead of registering it to the RGB camera
        #[arg(long)]
        no_registered: bool,

        /// A YOLO `.pt` to run over each displayed colour frame; repeat for
        /// several. Without it, every `*.pt` in ./models/ is used
        #[arg(long, value_name = "FILE.pt")]
        model: Vec<PathBuf>,

        /// Where to look for models when --model is not given (default: models)
        #[arg(long, value_name = "DIR", default_value = "models")]
        models_dir: PathBuf,

        /// Confidence floor for the detector
        #[arg(long, default_value_t = 0.4)]
        conf: f32,

        /// Inference size handed to the detector
        #[arg(long, default_value_t = 640)]
        imgsz: u32,

        /// Do not run the detector at all
        #[arg(long)]
        no_detect: bool,

        /// Python that has ultralytics installed (default: $INU_R132_PYTHON, then
        /// a .venv next to the program, then python3 on PATH)
        #[arg(long, value_name = "PYTHON")]
        python: Option<PathBuf>,

        /// The detector sidecar script (default: inu_yolo_detector.py next to the
        /// program, or in yolo-cube-detect/)
        #[arg(long, value_name = "SCRIPT")]
        detector: Option<PathBuf>,

        /// RGB channel id to stream from (default: auto detect)
        #[arg(long, allow_negative_numbers = true)]
        channel: Option<i32>,
    },

    /// Take one or more photos and save them as JPEG under `shot/` next to the
    /// program, each named after its capture timestamp. Handy for collecting a
    /// dataset (for example to train an object detector on the colour camera)
    #[command(disable_help_flag = true)]
    Shot {
        /// Directory to write to (created when missing); defaults to `shot/`
        /// next to the program
        #[arg(long, value_name = "DIR")]
        dir: Option<PathBuf>,

        /// How many photos to take
        #[arg(long, short = 'n', default_value_t = 1, value_parser = clap::value_parser!(u32).range(1..))]
        count: u32,

        /// Milliseconds between photos when taking more than one
        #[arg(long, default_value_t = 500)]
        interval: u64,

        /// Milliseconds to let auto exposure settle before the first photo
        #[arg(long, default_value_t = 500)]
        warmup: u64,

        /// JPEG quality, 1..=100 (photos default higher than the live stream)
        #[arg(long, default_value_t = 95, value_parser = clap::value_parser!(u8).range(1..=100))]
        quality: u8,

        /// Do not start InuService; connect to the already running daemon
        #[arg(long)]
        attach: bool,

        /// Save a synthetic test pattern instead of using the camera, for
        /// checking where the files land without any hardware
        #[arg(long)]
        mock: bool,

        /// InuService name to connect to (default: auto)
        #[arg(long, value_name = "NAME")]
        service: Option<String>,

        /// Pixel format requested from the SDK
        #[arg(long, value_enum, default_value_t = FormatArg::Bgra)]
        format: FormatArg,

        /// RGB channel id to stream from (default: auto detect)
        #[arg(long, allow_negative_numbers = true)]
        channel: Option<i32>,
    },

    /// Detect the cubes and print where they are and how far away, as JSON on
    /// stdout (one object per line; logs go to stderr). Opens the local camera,
    /// or scans a running `serve` with --remote
    #[command(disable_help_flag = true)]
    Scan {
        /// A YOLO `.pt` to run; repeat for several. Without it, every `*.pt` in
        /// the --models-dir directory is used
        #[arg(long, value_name = "FILE.pt")]
        model: Vec<PathBuf>,

        /// Where to look for models when --model is not given
        #[arg(long, value_name = "DIR", default_value = "models")]
        models_dir: PathBuf,

        /// Confidence floor for the detector
        #[arg(long, default_value_t = 0.4)]
        conf: f32,

        /// Inference size handed to the detector
        #[arg(long, default_value_t = 640)]
        imgsz: u32,

        /// How many scans to print
        #[arg(long, short = 'n', default_value_t = 1, value_parser = clap::value_parser!(u32).range(1..))]
        count: u32,

        /// Milliseconds to let the streams settle before the first scan, so the
        /// frame is not the sensor's boot frame and the depth stream has
        /// produced something to measure against
        #[arg(long, default_value_t = 500)]
        warmup: u64,

        /// Milliseconds between scans when printing more than one
        #[arg(long, default_value_t = 500)]
        interval: u64,

        /// How long to wait for the detector to answer one frame
        #[arg(long, value_name = "MS", default_value_t = 30000)]
        timeout: u64,

        /// Indent the JSON instead of one compact object per line
        #[arg(long)]
        pretty: bool,

        /// Scan a stream served by a `serve` instead of the local camera. Without
        /// a value it uses 0.0.0.0:5534, i.e. a serve on this machine
        #[arg(
            long,
            value_name = "HOST:PORT",
            num_args = 0..=1,
            default_missing_value = "0.0.0.0:5534"
        )]
        remote: Option<String>,

        /// Do not start InuService; connect to the already running daemon
        #[arg(long)]
        attach: bool,

        /// InuService name to connect to (default: auto)
        #[arg(long, value_name = "NAME")]
        service: Option<String>,

        /// Python that has ultralytics installed (default: $INU_R132_PYTHON, then
        /// a .venv next to the program, then python3 on PATH)
        #[arg(long, value_name = "PYTHON")]
        python: Option<PathBuf>,

        /// The detector sidecar script (default: inu_yolo_detector.py next to the
        /// program, or in yolo-cube-detect/)
        #[arg(long, value_name = "SCRIPT")]
        detector: Option<PathBuf>,

        /// Pixel format requested from the SDK
        #[arg(long, value_enum, default_value_t = FormatArg::Bgra)]
        format: FormatArg,

        /// Stream raw depth instead of registering it to the RGB camera. The boxes
        /// come from the colour image, so unregistered depth does not line up and
        /// the distances will be wrong
        #[arg(long)]
        no_registered: bool,

        /// RGB channel id to stream from (default: auto detect)
        #[arg(long, allow_negative_numbers = true)]
        channel: Option<i32>,
    },

    /// Stop Inuitive's InuService daemon
    #[command(disable_help_flag = true)]
    ServiceStop,

    /// Open the sensor and list every channel and sensor the SDK reports, as
    /// JSON on stdout. Use it to see whether this device has a depth, IR or
    /// point-cloud channel, and as a basic connectivity check
    #[command(disable_help_flag = true)]
    Probe {
        /// Do not start InuService; connect to the already running daemon
        #[arg(long)]
        attach: bool,

        /// InuService name to connect to (default: auto)
        #[arg(long, value_name = "NAME")]
        service: Option<String>,
    },
}
